version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: reddybalu2013/devops:1.0.0 
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "1100:8080"
    networks:
      - webnet

networks:
  webnet: